---
docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin
  - docker-ce-rootless-extras

docker_sdk_pip_packages:
  - docker
  - requests
  - dbus-python

virtualenv: "{{ kolla_docker_sdk_virtualenv | default(None) }}"
